# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@main
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # basic config
          user: gusluchetti
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Amsterdam
          config_display: columns
          # achievements
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          # iso commit calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          # languages
          plugin_languages: yes
          plugin_languages_analysis_timeout: 20
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_ignored: java
          plugin_languages_limit: 5
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          # plugin_languages_indepth: true
          # licenses
          plugin_licenses: true
          plugin_licenses_ratio: yes
          # extras
          plugin_fortune: yes
          plugin_gists: yes
          # leetcode
          plugin_leetcode: yes
          plugin_leetcode_limit_recent: 2
          plugin_leetcode_limit_skills: 10
          plugin_leetcode_sections: solved
          plugin_leetcode_user: .user.login
